export enum Color {
    Primary = "var(--primary)",
    SecondaryLight = "var(--secondary-light)",
    Secondary = "var(--secondary)",
    Black = "var(--black)",
    White = "var(--white)",
    Dark = "var(--dark)",
    Graphite = "var(--graphite)",
    Error = "var(--error)",
    Light = "var(--light)",
    Green = "var(--green)",
    Yellow = "var(--yellow)",
    Orange = "var(--orange)",
    Border = "var(--border)",
  }